dist: focal # https://docs.travis-ci.com/user/reference/focal/
language: java
jdk: openjdk10 # https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
sudo: false # see https://docs.travis-ci.com/user/reference/overview/
env:
  - TRAVIS_TAG=00.01 # see https://docs.travis-ci.com/user/environment-variables/
install: true # Without that statement, Travis will run 'mvn install' on pom.xml before the script step.  
script: 
  - mvn -f pom_travis.xml clean package
after_script:  
  - echo "TRAVIS_TAG = ${TRAVIS_TAG}"
#  - echo "GITHUB_OAUTH_TOKEN = ${GITHUB_OAUTH_TOKEN}" # print out: GITHUB_OAUTH_TOKEN = [secure]
deploy: # see https://docs.travis-ci.com/user/deployment/releases/ 
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: "target/json-validator-jar-with-dependencies.jar"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true # see https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
