language: java
jdk: oraclejdk8
sudo: false
install: true # The install step runs before script step, and with Maven you don't usually need the install step, at least I personally haven't ever found it useful — Maven will download dependencies on script step anyway
script: mvn -f pom_travis.xml clean verify
