language: java
jdk: oraclejdk8 # see https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
sudo: false # see https://docs.travis-ci.com/user/reference/overview/
env:
  - TRAVIS_TAG=00.01 # see https://docs.travis-ci.com/user/environment-variables/
install: true # The install step runs before script step, and with Maven you don't usually need the install step, at least I personally haven't ever found it useful — Maven will download dependencies on script step anyway
script: 
  - mvn -f pom_travis.xml clean verify
after_script:  
  - echo "TRAVIS_TAG = ${TRAVIS_TAG} \${TRAVIS_TAG} $TRAVIS_TAG \$TRAVIS_TA"
  - echo "GITHUB_OAUTH_TOKEN = ${GITHUB_OAUTH_TOKEN}"
deploy: # see https://docs.travis-ci.com/user/deployment/releases/ 
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: "target/po-test-json-validator-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true # see https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
