version: 2.1
jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  print-a-message:
    docker:
      - image: cimg/base:2022.03
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            java --version
            mvn -v
            mvn -f pom_circleci.xml test
      - run:
          name: Packaging
          command: |
            mvn -Dmaven.test.skip=true -f pom_circleci.xml clean package
            mkdir artifacts
            ls -la target || ls -la
            cp target/*.jar artifacts/          
      - run:
          name: Outdated
          command: mvn -f pom_circleci.xml versions:display-dependency-updates
  publish-github-release:
    docker:
      - image: circleci/golang:1.17
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            # see https://github.com/tcnksm/ghr/releases
            go install github.com/tcnksm/ghr@latest
            # VERSION=$(my-binary --version)
            # VERSION=$(xmlstarlet sel -N mvn='http://maven.apache.org/POM/4.0.0' -t -m '/mvn:project/mvn:version' -v . -n <pom.xml)
            VERSION=${CIRCLE_BRANCH}-release
            # see https://circleci.com/docs/variables/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ${VERSION} ./artifacts/
workflows:
  build-test-and-deploy:
    # https://circleci.com/docs/workflows/
    jobs:
      - hello-job
      - print-a-message:
          message: Hello!
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/ 